apiVersion: v1
kind: Service
metadata:
  name: retail-forecaster-service
  namespace: retail-forecaster
  labels:
    app: retail-forecaster
spec:
  type: ClusterIP
  selector:
    app: retail-forecaster
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: retail-mock-api
  namespace: retail-forecaster
  labels:
    app: retail-mock-api
spec:
  type: ClusterIP
  selector:
    app: retail-mock-api
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: retail-forecaster-nodeport
  namespace: retail-forecaster
  labels:
    app: retail-forecaster
spec:
  type: NodePort
  selector:
    app: retail-forecaster
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
